sudo: required
services:
  - docker

script:
 - docker build -t dmgman/node .
 - docker images dmgman/node

before_deploy:
  - docker login --username=ltv88 --password=ZXCo9708

deploy:
  provider: script
  script: docker push dmgman/node
  on:
    branch: master
